# Day 5 - Laptop Price Prediction

In this notebook, the saved preprocessing pipeline and tuned Random Forest model will be loaded and used to predict the price of a new laptop.

In [1]:
import pandas as pd
import numpy as np
import joblib

## 1. Loading the Saved Model

The tuned Random Forest model saved during Day 4 is loaded using Joblib.

In [2]:
model = joblib.load(
    r"D:\Smart-Laptop-Price-Predictor\models\laptop_price_model.pkl"
)

preprocessor = joblib.load(
    r"D:\Smart-Laptop-Price-Predictor\models\preprocessor.pkl"
)

print("Model loaded successfully!")
print("Preprocessor loaded successfully!")

Model loaded successfully!
Preprocessor loaded successfully!

## 2. Creating a New Laptop Sample

A sample laptop is created using the same input features used during model training.

In [3]:
new_laptop = pd.DataFrame({
    "Company": ["Dell"],
    "TypeName": ["Notebook"],
    "Inches": [15.6],
    "CPU_Company": ["Intel"],
    "CPU_Frequency (GHz)": [2.5],
    "RAM (GB)": [8],
    "GPU_Company": ["Intel"],
    "Weight (kg)": [2.0],
    "SSD_GB": [256],
    "HDD_GB": [0],
    "Flash_GB": [0],
    "Hybrid_GB": [0],
    "Total_Storage_GB": [256],
    "Storage_Type": ["SSD"],
    "Resolution_Width": [1920],
    "Resolution_Height": [1080],
    "Touchscreen": [0],
    "IPS": [0],
    "CPU_Family": ["Core i5"],
    "GPU_Family": ["Intel HD"],
    "OS_Family": ["Windows"]
})

new_laptop

,Company,TypeName,Inches,CPU_Company,CPU_Frequency (GHz),RAM (GB),GPU_Company,Weight (kg),SSD_GB,HDD_GB,...,Hybrid_GB,Total_Storage_GB,Storage_Type,Resolution_Width,Resolution_Height,Touchscreen,IPS,CPU_Family,GPU_Family,OS_Family
0,Dell,Notebook,15.6,Intel,2.5,8,Intel,2.0,256,0,...,0,256,SSD,1920,1080,0,0,Core i5,Intel HD,Windows

## 3. Preprocessing the New Laptop

The new laptop data is transformed using the same preprocessing pipeline that was fitted during model training.

In [4]:
new_laptop_processed = preprocessor.transform(new_laptop)

print("Processed shape:", new_laptop_processed.shape)

Processed shape: (1, 80)

## 4. Predicting Laptop Price

The processed laptop features are passed to the tuned Random Forest model to predict the laptop's price.

In [5]:
predicted_price = model.predict(new_laptop_processed)

print("Predicted Price (€):", predicted_price[0])

Predicted Price (€): 942.3411559394206

## 5. Final Prediction

The predicted laptop price is displayed in a user-friendly format.

In [6]:
price = predicted_price[0]

print(f"Predicted Laptop Price: €{price:,.2f}")

Predicted Laptop Price: €942.34

## 6. Testing Multiple Laptop Predictions

Multiple laptop configurations are tested using the same saved preprocessing pipeline and trained Random Forest model.

In [7]:
laptops = pd.DataFrame([
    {
        "Company": "Dell",
        "TypeName": "Notebook",
        "Inches": 15.6,
        "CPU_Company": "Intel",
        "CPU_Frequency (GHz)": 2.5,
        "RAM (GB)": 8,
        "GPU_Company": "Intel",
        "Weight (kg)": 2.0,
        "SSD_GB": 256,
        "HDD_GB": 0,
        "Flash_GB": 0,
        "Hybrid_GB": 0,
        "Total_Storage_GB": 256,
        "Storage_Type": "SSD",
        "Resolution_Width": 1920,
        "Resolution_Height": 1080,
        "Touchscreen": 0,
        "IPS": 0,
        "CPU_Family": "Core i5",
        "GPU_Family": "Intel HD",
        "OS_Family": "Windows"
    },
    {
        "Company": "Lenovo",
        "TypeName": "Notebook",
        "Inches": 15.6,
        "CPU_Company": "Intel",
        "CPU_Frequency (GHz)": 2.7,
        "RAM (GB)": 16,
        "GPU_Company": "Intel",
        "Weight (kg)": 1.8,
        "SSD_GB": 512,
        "HDD_GB": 0,
        "Flash_GB": 0,
        "Hybrid_GB": 0,
        "Total_Storage_GB": 512,
        "Storage_Type": "SSD",
        "Resolution_Width": 1920,
        "Resolution_Height": 1080,
        "Touchscreen": 0,
        "IPS": 0,
        "CPU_Family": "Core i7",
        "GPU_Family": "Intel HD",
        "OS_Family": "Windows"
    },
    {
        "Company": "Asus",
        "TypeName": "Gaming",
        "Inches": 15.6,
        "CPU_Company": "Intel",
        "CPU_Frequency (GHz)": 2.8,
        "RAM (GB)": 16,
        "GPU_Company": "Nvidia",
        "Weight (kg)": 2.5,
        "SSD_GB": 512,
        "HDD_GB": 1000,
        "Flash_GB": 0,
        "Hybrid_GB": 0,
        "Total_Storage_GB": 1512,
        "Storage_Type": "SSD + HDD",
        "Resolution_Width": 1920,
        "Resolution_Height": 1080,
        "Touchscreen": 0,
        "IPS": 0,
        "CPU_Family": "Core i7",
        "GPU_Family": "Nvidia GTX",
        "OS_Family": "Windows"
    }
])

laptops

,Company,TypeName,Inches,CPU_Company,CPU_Frequency (GHz),RAM (GB),GPU_Company,Weight (kg),SSD_GB,HDD_GB,...,Hybrid_GB,Total_Storage_GB,Storage_Type,Resolution_Width,Resolution_Height,Touchscreen,IPS,CPU_Family,GPU_Family,OS_Family
0,Dell,Notebook,15.6,Intel,2.5,8,Intel,2.0,256,0,...,0,256,SSD,1920,1080,0,0,Core i5,Intel HD,Windows
1,Lenovo,Notebook,15.6,Intel,2.7,16,Intel,1.8,512,0,...,0,512,SSD,1920,1080,0,0,Core i7,Intel HD,Windows
2,Asus,Gaming,15.6,Intel,2.8,16,Nvidia,2.5,512,1000,...,0,1512,SSD + HDD,1920,1080,0,0,Core i7,Nvidia GTX,Windows

In [8]:
laptops_processed = preprocessor.transform(laptops)

predictions = model.predict(laptops_processed)

laptops["Predicted_Price_Euro"] = predictions

laptops[["Company", "TypeName", "RAM (GB)", "CPU_Family", "Predicted_Price_Euro"]]

  Company  TypeName  RAM (GB) CPU_Family  Predicted_Price_Euro
0    Dell  Notebook         8    Core i5            942.341156
1  Lenovo  Notebook        16    Core i7           1660.964688
2    Asus    Gaming        16    Core i7           1744.417951

## 7. Creating a Reusable Prediction Function

A reusable function is created so that laptop specifications can be provided as input and the trained model can directly return the predicted price.

In [9]:
def predict_laptop_price(laptop_data):
    laptop_df = pd.DataFrame([laptop_data])

    processed_data = preprocessor.transform(laptop_df)

    prediction = model.predict(processed_data)

    return prediction[0]

In [10]:
laptop = {
    "Company": "HP",
    "TypeName": "Notebook",
    "Inches": 15.6,
    "CPU_Company": "Intel",
    "CPU_Frequency (GHz)": 2.5,
    "RAM (GB)": 8,
    "GPU_Company": "Intel",
    "Weight (kg)": 2.0,
    "SSD_GB": 256,
    "HDD_GB": 0,
    "Flash_GB": 0,
    "Hybrid_GB": 0,
    "Total_Storage_GB": 256,
    "Storage_Type": "SSD",
    "Resolution_Width": 1920,
    "Resolution_Height": 1080,
    "Touchscreen": 0,
    "IPS": 0,
    "CPU_Family": "Core i5",
    "GPU_Family": "Intel HD",
    "OS_Family": "Windows"
}

price = predict_laptop_price(laptop)

print(f"Predicted Price: €{price:,.2f}")

Predicted Price: €859.04

## 8. Testing the Prediction Function

The prediction function is tested with different laptop configurations to verify that it produces different price predictions based on the specifications.

In [11]:
test_laptops = [
    {
        "Company": "Acer",
        "TypeName": "Notebook",
        "Inches": 15.6,
        "CPU_Company": "Intel",
        "CPU_Frequency (GHz)": 2.0,
        "RAM (GB)": 4,
        "GPU_Company": "Intel",
        "Weight (kg)": 2.2,
        "SSD_GB": 128,
        "HDD_GB": 0,
        "Flash_GB": 0,
        "Hybrid_GB": 0,
        "Total_Storage_GB": 128,
        "Storage_Type": "SSD",
        "Resolution_Width": 1366,
        "Resolution_Height": 768,
        "Touchscreen": 0,
        "IPS": 0,
        "CPU_Family": "Core i3",
        "GPU_Family": "Intel HD",
        "OS_Family": "Windows"
    },
    
    {
        "Company": "Dell",
        "TypeName": "Notebook",
        "Inches": 15.6,
        "CPU_Company": "Intel",
        "CPU_Frequency (GHz)": 2.7,
        "RAM (GB)": 16,
        "GPU_Company": "Intel",
        "Weight (kg)": 1.8,
        "SSD_GB": 512,
        "HDD_GB": 0,
        "Flash_GB": 0,
        "Hybrid_GB": 0,
        "Total_Storage_GB": 512,
        "Storage_Type": "SSD",
        "Resolution_Width": 1920,
        "Resolution_Height": 1080,
        "Touchscreen": 0,
        "IPS": 1,
        "CPU_Family": "Core i7",
        "GPU_Family": "Intel UHD",
        "OS_Family": "Windows"
    }
]

for i, laptop in enumerate(test_laptops, start=1):
    price = predict_laptop_price(laptop)
    print(f"Laptop {i} Predicted Price: €{price:,.2f}")

Laptop 1 Predicted Price: €475.78
Laptop 2 Predicted Price: €1,562.92

## 9. Storing Prediction Results

The predictions from multiple laptop configurations are stored in a DataFrame for easy comparison and analysis.

In [12]:
prediction_results = []

for i, laptop in enumerate(test_laptops, start=1):
    price = predict_laptop_price(laptop)
    
    prediction_results.append({
        "Laptop": f"Laptop {i}",
        "Company": laptop["Company"],
        "RAM (GB)": laptop["RAM (GB)"],
        "CPU_Family": laptop["CPU_Family"],
        "Storage_Type": laptop["Storage_Type"],
        "Predicted_Price_Euro": round(price, 2)
    })

prediction_results_df = pd.DataFrame(prediction_results)

prediction_results_df

     Laptop Company  RAM (GB) CPU_Family Storage_Type  Predicted_Price_Euro
0  Laptop 1    Acer         4    Core i3          SSD                475.78
1  Laptop 2    Dell        16    Core i7          SSD               1562.92

## 10. Saving Prediction Results

The prediction results are saved as a CSV file for future reference.

In [13]:
prediction_results_df.to_csv(
    r"D:\Smart-Laptop-Price-Predictor\data\prediction_results.csv",
    index=False
)

print("Prediction results saved successfully!")

Prediction results saved successfully!